In [16]:
%load_ext autoreload
%autoreload 2
import sys
import os
sys.path.append(os.path.abspath(".."))
import solver
import pandas as pd
import numpy as np

n_all = pd.read_excel("/Users/raymondiacobacci/LeiteLab-6_8/n-allHTMats-2.xlsx")
k_all = pd.read_excel("/Users/raymondiacobacci/LeiteLab-6_8/k-allHTMats.xlsx")

test_wavelength_index = 650
grating_period = 1

n_harmonics = 0

er = np.ones(shape = (100,)) #+ 1j * np.ones(shape=(100,))
# er[50] = 2
ur = np.ones(shape = (100,))
air_layer = solver.Layer(permittivity = np.ones(shape = (100,)) , permeability = np.ones(shape = (100,)), thickness = 9, n_harmonics = n_harmonics)
aln_grating = solver.Layer(
    permittivity=er,
    permeability=ur,
    thickness=10,
    n_harmonics=n_harmonics,
)
my_solver = solver.Solver(layer_stack = [air_layer, aln_grating, air_layer], grating_period = grating_period, wavelength = test_wavelength_index, n_harmonics = n_harmonics)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Layer 1
[[0.99533163+0.09651392j 0.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.99533163+0.09651392j 0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.99533163-0.09651392j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  0.99533163-0.09651392j]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
----------------------------------------------------------------------------------------------------
Layer 2
[[0.99621806+0.08688825j 0.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.99621806+0.08688825j 0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.99621806-0.08688825j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  0.99621806-0.08688825j]]
[[1.

In [154]:
a=(-1+np.sqrt(2))/2
print(a)
2*np.sqrt(2)/(1+np.sqrt(2))
2/(np.sqrt(2)+1)
((np.sqrt(2)-1)/(np.sqrt(2)+1))**2

0.20710678118654757


np.float64(0.029437251522859434)

In [116]:
2/(np.sqrt(2)+1)

np.float64(0.8284271247461902)

In [ ]:

a=0.101+0.18081j
b=-0.588673-1.053836j
c=0.588673-1.053836j
d=0.101+0.18081j
a-b*c/d

(3.5320225238024077-5.961399728007062j)